# Generated by Django 6.0.3 on 2026-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=150)),
                ('language_requirement', models.CharField(max_length=100)),
                ('funding_amount', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('application_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
